//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  F:\PHEactProject\Source\Project\UGUI\CMMProgramUI.cpp
//
//        This file was generated by the NX Block Styler
//        Created by: PENGHUI
//              Version: NX 6
//              Date: 08-06-2018  (Format: mm-dd-yyyy)
//              Time: 13:53 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "CMMProgramUI.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(CMMProgramUI::theSession) = NULL;
UI *(CMMProgramUI::theUI) = NULL;

//------------------------------------------------------------------------------
// Declaration of global variables
//------------------------------------------------------------------------------
CMMProgramUI *theCMMProgramUI;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
CMMProgramUI::CMMProgramUI()
{
    try
    {
        // Initialize the NX Open C++ API environment
        CMMProgramUI::theSession = NXOpen::Session::GetSession();
        CMMProgramUI::theUI = UI::GetUI();
        theDialogName = "CMMProgramUI.dlx";
        theDialog = CMMProgramUI::theUI->CreateDialog(theDialogName.c_str());
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &CMMProgramUI::apply_cb));
        theDialog->AddUpdateHandler(make_callback(this, &CMMProgramUI::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &CMMProgramUI::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &CMMProgramUI::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
CMMProgramUI::~CMMProgramUI()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    try
    {
        theCMMProgramUI = new CMMProgramUI();
        // The following method shows the dialog immediately
        theCMMProgramUI->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CMMProgramUI::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    delete theCMMProgramUI;
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CMMProgramUI::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

int CMMProgramUI::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CMMProgramUI::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void CMMProgramUI::initialize_cb()
{
    try
    {
        group0 = theDialog->TopBlock()->FindBlock("group0");
        selectCuprum = theDialog->TopBlock()->FindBlock("selectCuprum");
        enumSelectTool = theDialog->TopBlock()->FindBlock("enumSelectTool");
        group = theDialog->TopBlock()->FindBlock("group");
        drawingArea0 = theDialog->TopBlock()->FindBlock("drawingArea0");
        toggle0 = theDialog->TopBlock()->FindBlock("toggle0");
        btnAutoSelectPoint = theDialog->TopBlock()->FindBlock("btnAutoSelectPoint");
        selectionPoint = theDialog->TopBlock()->FindBlock("selectionPoint");
        tree_control0 = theDialog->TopBlock()->FindBlock("tree_control0");
        btnRemove = theDialog->TopBlock()->FindBlock("btnRemove");
        btnUP = theDialog->TopBlock()->FindBlock("btnUP");
        btnDown = theDialog->TopBlock()->FindBlock("btnDown");
        btnExport = theDialog->TopBlock()->FindBlock("btnExport");
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CMMProgramUI::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void CMMProgramUI::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CMMProgramUI::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int CMMProgramUI::apply_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CMMProgramUI::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int CMMProgramUI::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == selectCuprum)
        {
        //---------Enter your code here-----------
        }
        else if(block == enumSelectTool)
        {
        //---------Enter your code here-----------
        }
        else if(block == drawingArea0)
        {
        //---------Enter your code here-----------
        }
        else if(block == toggle0)
        {
        //---------Enter your code here-----------
        }
        else if(block == btnAutoSelectPoint)
        {
        //---------Enter your code here-----------
        }
        else if(block == selectionPoint)
        {
        //---------Enter your code here-----------
        }
        else if(block == tree_control0)
        {
        //---------Enter your code here-----------
        }
        else if(block == btnRemove)
        {
        //---------Enter your code here-----------
        }
        else if(block == btnUP)
        {
        //---------Enter your code here-----------
        }
        else if(block == btnDown)
        {
        //---------Enter your code here-----------
        }
        else if(block == btnExport)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        CMMProgramUI::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}
