//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  F:\PHEactProject\Source\Project\UGUI\CMMProgramUI.java
//
//        This file was generated by the NX Block Styler
//        Created by: PENGHUI
//              Version: NX 6
//              Date: 08-06-2018  (Format: mm-dd-yyyy)
//              Time: 13:57 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains JAVA source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
import java.rmi.RemoteException;
import nxopen.*;
import nxopen.blockstyler.*;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class CMMProgramUI implements BlockDialog.Initialize, BlockDialog.DialogShown, BlockDialog.Update
{
    //class members
    public static Session theSession = null;
    public static UI theUI = null;
    static CMMProgramUI theCMMProgramUI;
    private String theDialogName;
    private nxopen.blockstyler.BlockDialog theDialog;
    private nxopen.blockstyler.UIBlock group0;// Block type: Group
    private nxopen.blockstyler.UIBlock selectCuprum;// Block type: Selection
    private nxopen.blockstyler.UIBlock enumSelectTool;// Block type: Enumeration
    private nxopen.blockstyler.UIBlock group;// Block type: Group
    private nxopen.blockstyler.UIBlock drawingArea0;// Block type: Drawing Area
    private nxopen.blockstyler.UIBlock toggle0;// Block type: Toggle
    private nxopen.blockstyler.UIBlock btnAutoSelectPoint;// Block type: Button
    private nxopen.blockstyler.UIBlock selectionPoint;// Block type: Selection
    private nxopen.blockstyler.UIBlock tree_control0;// Block type: Tree Control
    private nxopen.blockstyler.UIBlock btnRemove;// Block type: Button
    private nxopen.blockstyler.UIBlock btnUP;// Block type: Button
    private nxopen.blockstyler.UIBlock btnDown;// Block type: Button
    private nxopen.blockstyler.UIBlock btnExport;// Block type: Button
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesEnabled
    //------------------------------------------------------------------------------
    public static final int              SnapPointTypesEnabled_UserDefined = (1 << 0);
    public static final int                 SnapPointTypesEnabled_Inferred = (1 << 1);
    public static final int           SnapPointTypesEnabled_ScreenPosition = (1 << 2);
    public static final int                 SnapPointTypesEnabled_EndPoint = (1 << 3);
    public static final int                 SnapPointTypesEnabled_MidPoint = (1 << 4);
    public static final int             SnapPointTypesEnabled_ControlPoint = (1 << 5);
    public static final int             SnapPointTypesEnabled_Intersection = (1 << 6);
    public static final int                SnapPointTypesEnabled_ArcCenter = (1 << 7);
    public static final int            SnapPointTypesEnabled_QuadrantPoint = (1 << 8);
    public static final int            SnapPointTypesEnabled_ExistingPoint = (1 << 9);
    public static final int             SnapPointTypesEnabled_PointonCurve = (1 <<10);
    public static final int           SnapPointTypesEnabled_PointonSurface = (1 <<11);
    public static final int         SnapPointTypesEnabled_PointConstructor = (1 <<12);
    public static final int     SnapPointTypesEnabled_TwocurveIntersection = (1 <<13);
    public static final int             SnapPointTypesEnabled_TangentPoint = (1 <<14);
    public static final int                    SnapPointTypesEnabled_Poles = (1 <<15);
    //------------------------------------------------------------------------------
    //Bit Option for Property: SnapPointTypesOnByDefault
    //------------------------------------------------------------------------------
    public static final int             SnapPointTypesOnByDefault_EndPoint = (1 << 3);
    public static final int             SnapPointTypesOnByDefault_MidPoint = (1 << 4);
    public static final int         SnapPointTypesOnByDefault_ControlPoint = (1 << 5);
    public static final int         SnapPointTypesOnByDefault_Intersection = (1 << 6);
    public static final int            SnapPointTypesOnByDefault_ArcCenter = (1 << 7);
    public static final int        SnapPointTypesOnByDefault_QuadrantPoint = (1 << 8);
    public static final int        SnapPointTypesOnByDefault_ExistingPoint = (1 << 9);
    public static final int         SnapPointTypesOnByDefault_PointonCurve = (1 <<10);
    public static final int       SnapPointTypesOnByDefault_PointonSurface = (1 <<11);
    public static final int     SnapPointTypesOnByDefault_PointConstructor = (1 <<12);
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public CMMProgramUI() throws Exception, RemoteException
    {
        try
        {
            theSession = (Session)SessionFactory.get("Session");
            theUI = (UI)SessionFactory.get("UI");
            theDialogName = "CMMProgramUI.dlx";
            theDialog = theUI.createDialog(theDialogName);
            theDialog.addApplyHandler(this);
            theDialog.addUpdateHandler(this);
            theDialog.addInitializeHandler(this);
            theDialog.addDialogShownHandler(this);
        }
        catch(Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw new Exception(ex);
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void main(String [] argv) throws Exception
    {
        try
        {
            theCMMProgramUI = new CMMProgramUI();
            // The following method shows the dialog immediately
            theCMMProgramUI.show();
        }
        catch(Exception ex)
        {
            //---- Enter your exception handling code here -----
             theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.INFORMATION, ex.getMessage());
        }
        finally
        {
            theCMMProgramUI.dispose();
        }
    }
    
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static final int getUnloadOption()
    {
        //return BaseSession.LibraryUnloadOption.EXPLICITLY;
         return BaseSession.LibraryUnloadOption.IMMEDIATELY;
        // return BaseSession.LibraryUnloadOption.ATTERMINATION;
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void unloadLibrary() throws NXException, RemoteException
    {
        try
        {
        }
        catch(Exception ex)
        {
            //---- Enter your exception handling code here -----
             theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.INFORMATION, ex.getMessage());
        }
    }
    
    //------------------------------------------------------------------------------
    //This method shows the dialog on the screen
    //------------------------------------------------------------------------------
    public int show() throws NXException, RemoteException
    {
        try
        {
            theDialog.show();
        }
        catch(Exception ex)
        {
            //---- Enter your exception handling code here -----
             theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.INFORMATION, ex.getMessage());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: dispose
    //------------------------------------------------------------------------------
    public void dispose() throws NXException, RemoteException
    {
        if(theDialog != null)
        {
            theDialog.dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize
    //------------------------------------------------------------------------------
    public void initialize() throws NXException, RemoteException
    {
        try
        {
            group0 = theDialog.topBlock().findBlock("group0");
            selectCuprum = theDialog.topBlock().findBlock("selectCuprum");
            enumSelectTool = theDialog.topBlock().findBlock("enumSelectTool");
            group = theDialog.topBlock().findBlock("group");
            drawingArea0 = theDialog.topBlock().findBlock("drawingArea0");
            toggle0 = theDialog.topBlock().findBlock("toggle0");
            btnAutoSelectPoint = theDialog.topBlock().findBlock("btnAutoSelectPoint");
            selectionPoint = theDialog.topBlock().findBlock("selectionPoint");
            tree_control0 = theDialog.topBlock().findBlock("tree_control0");
            btnRemove = theDialog.topBlock().findBlock("btnRemove");
            btnUP = theDialog.topBlock().findBlock("btnUP");
            btnDown = theDialog.topBlock().findBlock("btnDown");
            btnExport = theDialog.topBlock().findBlock("btnExport");
        }
        catch(Exception ex)
        {
            //---- Enter your exception handling code here -----
             theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.INFORMATION, ex.getMessage());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown() throws NXException, RemoteException
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch(Exception ex)
        {
            //---- Enter your exception handling code here -----
             theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.INFORMATION, ex.getMessage());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply
    //Following callback is associated with the "theDialog" Block.
    //------------------------------------------------------------------------------
    public int apply() throws NXException, RemoteException
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch(Exception ex)
        {
            //---- Enter your exception handling code here -----
             theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.INFORMATION, ex.getMessage());
        }
        return 0;
    }
    //------------------------------------------------------------------------------
    //Callback Name: update
    //Following callback is associated with the "theDialog" Block.
    //------------------------------------------------------------------------------
    public int update( nxopen.blockstyler.UIBlock block) throws NXException, RemoteException
    {
        try
        {
            if(block == selectCuprum)
            {
            //---------Enter your code here-----------
            }
            else if(block == enumSelectTool)
            {
            //---------Enter your code here-----------
            }
            else if(block == drawingArea0)
            {
            //---------Enter your code here-----------
            }
            else if(block == toggle0)
            {
            //---------Enter your code here-----------
            }
            else if(block == btnAutoSelectPoint)
            {
            //---------Enter your code here-----------
            }
            else if(block == selectionPoint)
            {
            //---------Enter your code here-----------
            }
            else if(block == tree_control0)
            {
            //---------Enter your code here-----------
            }
            else if(block == btnRemove)
            {
            //---------Enter your code here-----------
            }
            else if(block == btnUP)
            {
            //---------Enter your code here-----------
            }
            else if(block == btnDown)
            {
            //---------Enter your code here-----------
            }
            else if(block == btnExport)
            {
            //---------Enter your code here-----------
            }
        }
        catch(Exception ex)
        {
            //---- Enter your exception handling code here -----
             theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.INFORMATION, ex.getMessage());
        }
        return 0;
    }
    
}
